name: Create Release and Publish to PyPI

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  create-release-and-publish:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    environment:
      name: pypi
      url: https://pypi.org/p/hyperion-sdk
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - uses: ./.github/actions/install-all
        with:
          python-version: "3.12"

      - name: Get Current Version
        id: get_version
        run: |
          VERSION=$(poetry version --short)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build package
        run: poetry build

      - name: Create and Push Tag
        run: |
          git tag "v${{steps.get_version.outputs.version}}"
          git push origin "v${{steps.get_version.outputs.version}}"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{steps.get_version.outputs.version}}"
          name: "Release ${{steps.get_version.outputs.version}}"
          files: |
            dist/hyperion_sdk-${{steps.get_version.outputs.version}}.tar.gz
            dist/hyperion_sdk-${{steps.get_version.outputs.version}}-py3-none-any.whl
          draft: false
          prerelease: false
          generate_release_notes: true
