name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: ./.github/actions/install-all
        with:
          python-version: "${{matrix.python-version}}"
      - name: Run pre-commit
        run: pre-commit run -a
